# Generated by Django 3.1.5 on 2021-01-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sberbank', '0007_auto_20210122_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='details'),
        ),
    ]
